###
 # @Author: Ricken
 # @Email: me@ricken.cn
 # @Date: 2025-08-10 14:58:10
 # @LastEditTime: 2025-08-10 15:26:18
 # @FilePath: /cy_frame/script/fonts.sh
 # @Description: 生成fontconfig配置文件，便于X64查看效果
 # @BugList: 
 # 
 # Copyright (c) 2025 by Ricken, All Rights Reserved. 
 # 
### 
#!/bin/sh
#set -x

# 获取脚本所在的目录并切换到该目录
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# 定义字体目录的路径
FONT_DIR="$(realpath "$SCRIPT_DIR/../fonts")"

# 定义字体头文件目录位置
FONT_HEADER_DIR="$(realpath "$SCRIPT_DIR/../config")"

# 创建 fonts.conf 文件并写入内容
cat <<EOL > "$FONT_DIR/fonts.conf"
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">

<!-- This document is automatically generated by Ricken. -->

<fontconfig>
    <dir>$FONT_DIR</dir>
</fontconfig>
EOL

# 生成fonts_info.h文件
cat <<EOL > "$FONT_HEADER_DIR/fonts_info.h"
// Automatically built by script

#ifndef __FONTS_INFO_H__
#define __FONTS_INFO_H__

#define FONTCONFIG_PATH "$FONT_DIR"

#endif // __FONTS_INFO_H__
EOL

# 输出log
echo "fonts.conf 文件已生成在 $FONT_DIR"
echo "fonts_info.h 文件已生成在 $FONT_HEADER_DIR"

